# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-29 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonanswer',
            name='correct',
            field=models.BooleanField(verbose_name='Correct answer'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='status',
            field=models.BooleanField(verbose_name='Publish status'),
        ),
    ]
