# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-29 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200529_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderanswer',
            name='number',
        ),
        migrations.AddField(
            model_name='orderanswer',
            name='number_1',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], null=True, verbose_name='Answer FIRST Position'),
        ),
        migrations.AddField(
            model_name='orderanswer',
            name='number_2',
            field=models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D')], null=True, verbose_name='Answer SECOND Position'),
        ),
    ]
