# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-19 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200819_2010'),
    ]

    def delete_all_subjects(apps, schema):
        Subject = apps.get_model('quiz', 'Subject')

        Subject.objects.all().delete()

    def reverse_delete_all_subjects(apps, schema):
        pass

    operations = [
        migrations.RunPython(delete_all_subjects, reverse_code=reverse_delete_all_subjects),
        migrations.AlterField(
            model_name='commonanswer',
            name='number',
            field=models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E')], verbose_name='Answer Order'),
        ),
        migrations.AlterField(
            model_name='mappinganswer',
            name='number_1',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (0, '0')], verbose_name='First chain'),
        ),
        migrations.AlterField(
            model_name='mappinganswer',
            name='number_2',
            field=models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E')], verbose_name='Second chain'),
        ),
        migrations.AlterField(
            model_name='orderanswer',
            name='number_1',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='Answer FIRST Position'),
        ),
        migrations.AlterField(
            model_name='orderanswer',
            name='number_2',
            field=models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D')], verbose_name='Answer SECOND Position'),
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.Test', verbose_name='Test'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.SlugField(verbose_name='Slug name'),
        ),
    ]
