# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-29 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200529_0205'),
    ]

    def add_numbers_order_answers(apps, schema):
        OrderAnswer = apps.get_model('quiz', 'OrderAnswer')

        for answer in OrderAnswer.objects.all():
            answer.number_1 = 0
            answer.number_2 = 0

    def reverse_add_numbers_common_answers(apps, schema):
        pass

    operations = [
        migrations.RunPython(add_numbers_order_answers, reverse_code=reverse_add_numbers_common_answers),
        migrations.AlterField(
            model_name='orderanswer',
            name='number_1',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='Answer FIRST Position'),
        ),
        migrations.AlterField(
            model_name='orderanswer',
            name='number_2',
            field=models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D')], verbose_name='Answer SECOND Position'),
        ),
    ]
