# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-20 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200819_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('test_time', models.SmallIntegerField(default=20, verbose_name='Test time')),
                ('number_of_common_questions', models.SmallIntegerField(verbose_name='Number of common questions')),
                ('number_of_order_questions', models.SmallIntegerField(verbose_name='Number of order questions')),
                ('number_of_mapping_questions', models.SmallIntegerField(verbose_name='Number of mapping questions')),
                ('coefficient_of_common_question', models.FloatField(verbose_name='coefficient per common questions')),
                ('coefficient_of_order_question', models.FloatField(verbose_name='coefficient per order questions')),
                ('coefficient_of_mapping_question', models.FloatField(verbose_name='coefficient per mapping questions')),
            ],
            options={
                'verbose_name': 'Test Parameter',
            },
        ),
        migrations.AddField(
            model_name='test',
            name='test_parameter',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.TestParameter', verbose_name='Test Parameter'),
        ),
    ]
