# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-28 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20200820_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearsubjectstatistics',
            name='percent_a',
            field=models.IntegerField(verbose_name='Percent of pupils that have A mark'),
        ),
        migrations.AlterField(
            model_name='yearsubjectstatistics',
            name='percent_b',
            field=models.IntegerField(verbose_name='Percent of pupils that have B mark'),
        ),
        migrations.AlterField(
            model_name='yearsubjectstatistics',
            name='percent_c',
            field=models.IntegerField(verbose_name='Percent of pupils that have C mark'),
        ),
    ]
