# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-02 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20200602_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonanswer',
            name='number',
            field=models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D')], verbose_name='Answer Order'),
        ),
    ]
