# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-02 20:32
from __future__ import unicode_literals

import centr_osvita.quiz.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200527_1927'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('quiz', '0007_auto_20200602_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'In Progress'), (1, 'Done'), (2, 'Suspend')], default=0, verbose_name='Status')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='profiles.Profile', verbose_name='Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='quiz.Subject', verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
            ],
            options={
                'verbose_name': 'Quiz Answer',
                'verbose_name_plural': 'Quiz Answers',
                'manager_inheritance_from_future': True,
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Done'), (2, 'Suspend')], default=0, verbose_name='Status')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='quiz.Question', verbose_name='Question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='quiz.Quiz', verbose_name='Quiz')),
            ],
            options={
                'verbose_name': 'Quiz Question',
                'verbose_name_plural': 'Quiz Questions',
            },
        ),
        migrations.CreateModel(
            name='QuizCommonAnswer',
            fields=[
                ('quizanswer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.QuizAnswer')),
                ('number', models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D')], verbose_name='Answer Order')),
            ],
            options={
                'verbose_name': 'Quiz Common Answer',
                'verbose_name_plural': 'Quiz Common Answers',
                'manager_inheritance_from_future': True,
            },
            bases=('quiz.quizanswer',),
        ),
        migrations.CreateModel(
            name='QuizMappingAnswer',
            fields=[
                ('quizanswer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.QuizAnswer')),
                ('number_1', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (0, '0')], verbose_name='First chain')),
                ('number_2', models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E')], verbose_name='Second chain')),
            ],
            options={
                'verbose_name': 'Quiz Mapping Answer',
                'verbose_name_plural': 'Quiz Mapping Answers',
                'manager_inheritance_from_future': True,
            },
            bases=('quiz.quizanswer',),
        ),
        migrations.CreateModel(
            name='QuizOrderAnswer',
            fields=[
                ('quizanswer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.QuizAnswer')),
                ('number_1', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='Answer FIRST Position')),
                ('number_2', models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D')], verbose_name='Answer SECOND Position')),
            ],
            options={
                'verbose_name': 'Quiz Order Answer',
                'verbose_name_plural': 'Quiz Order Answers',
                'manager_inheritance_from_future': True,
            },
            bases=('quiz.quizanswer',),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='answer',
            field=models.ForeignKey(on_delete=centr_osvita.quiz.models.NON_POLYMORPHIC_CASCADE, related_name='quiz_answers', to='quiz.Answer', verbose_name='Answer'),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_quiz.quizanswer_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='quiz_question',
            field=models.ForeignKey(on_delete=centr_osvita.quiz.models.NON_POLYMORPHIC_CASCADE, related_name='quiz_answers', to='quiz.QuizQuestion', verbose_name='Quiz Question'),
        ),
    ]
