# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-14 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20200814_1229'),
    ]

    def add_test_question_quiz(apps, schema):
        Question = apps.get_model('quiz', 'Question')
        Quiz = apps.get_model('quiz', 'Quiz')

        Question.objects.all().delete()
        Quiz.objects.all().delete()

    def reverse_add_test_question_quiz(apps, schema):
        pass

    operations = [
        migrations.RunPython(add_test_question_quiz, reverse_code=reverse_add_test_question_quiz),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.Test', verbose_name='Test'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='quiz.Test', verbose_name='Test'),
        ),
    ]
