# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-14 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_auto_20200814_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.SmallIntegerField(verbose_name='Year info')),
            ],
        ),
        migrations.CreateModel(
            name='YearSubjectStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_c', models.FloatField(verbose_name='Percent of pupils that have C mark')),
                ('percent_b', models.FloatField(verbose_name='Percent of pupils that have B mark')),
                ('percent_a', models.FloatField(verbose_name='Percent of pupils that have A mark')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='slug',
            field=models.SlugField(null=True, verbose_name='Slug name'),
        ),
        migrations.AddField(
            model_name='test',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='quiz.Subject', verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='yearsubjectstatistics',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='quiz.Subject', verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='yearsubjectstatistics',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='quiz.Year', verbose_name='Year'),
        ),
    ]
