# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-14 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_auto_20200814_1308'),
    ]

    def add_test_question_quiz(apps, schema):
        Subject = apps.get_model('quiz', 'Question')
        Test = apps.get_model('quiz', 'Test')

        Subject.objects.all().delete()
        Test.objects.all().delete()

    def reverse_add_test_question_quiz(apps, schema):
        pass

    operations = [
        migrations.RunPython(add_test_question_quiz, reverse_code=reverse_add_test_question_quiz),
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.SlugField(verbose_name='Slug name'),
        ),
        migrations.AlterField(
            model_name='test',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='quiz.Subject', verbose_name='Subject'),
        ),
    ]
