# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-09 10:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('full_name', models.CharField(help_text='Maximum length is 255 symbols', max_length=255, verbose_name='full name')),
                ('mother_full_name', models.CharField(blank=True, help_text='Maximum length is 255 symbols', max_length=255, null=True, verbose_name='Mother fullname')),
                ('mother_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, verbose_name='Mother phone')),
                ('father_full_name', models.CharField(blank=True, help_text='Maximum length is 255 symbols', max_length=255, null=True, verbose_name='Father fullname')),
                ('father_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, verbose_name='Father phone')),
                ('school_name', models.CharField(help_text='Maximum length is 255 symbols', max_length=255, verbose_name='School name')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
