# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-10 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200527_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='father_full_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='father_phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mother_full_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mother_phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='school_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='grade',
            field=models.IntegerField(blank=True, choices=[(9, '9'), (10, '10'), (11, '11')], null=True, verbose_name='Grade number'),
        ),
        migrations.AddField(
            model_name='profile',
            name='institution_name',
            field=models.CharField(help_text='Maximum length is 255 symbols', max_length=255, null=True, verbose_name='Institution name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='parent_full_name',
            field=models.CharField(blank=True, help_text='Maximum length is 255 symbols', max_length=255, null=True, verbose_name='Parent fullname'),
        ),
        migrations.AddField(
            model_name='profile',
            name='parent_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, verbose_name='Parent phone'),
        ),
    ]
