# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-19 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200710_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='institution_type',
            field=models.IntegerField(choices=[(1, 'School'), (2, 'Lyceum/Gymnasium'), (3, 'College'), (0, 'Other')], default=1, verbose_name='Institution type'),
        ),
    ]
