# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-28 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_institution_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('profiles', models.ManyToManyField(related_name='Profiles', to='profiles.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
