# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-13 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_userreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userreport',
            options={'verbose_name': 'User Report', 'verbose_name_plural': 'User Reports'},
        ),
    ]
