# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-13 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20200913_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreport',
            name='profiles',
            field=models.ManyToManyField(related_name='Профілі', to='profiles.Profile'),
        ),
    ]
