# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-09 11:03
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200409_1053'),
    ]

    def add_dumpy_phone_number(apps, schema):
        User = apps.get_model('users', 'User')

        for user in User.objects.all():
            user.phone = '+41524204242'
            user.save()

    def reverse_add_dumpy_phone_number(apps, schema):
        pass

    operations = [
        migrations.RunPython(add_dumpy_phone_number, reverse_code=reverse_add_dumpy_phone_number),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, unique=True),
        ),
    ]
